### ISSUE TITLE
Result is found in URE, but not returned as a result

### ISSUE THREAD

**Issue by Necr0x0Der** [singnet/atomspace#16] opened 2018-09-18 14:21 UTC
In our experiments with URE, we found a situation, when URE performs a correct inference sequence, but doesn't return the result. Here is the code:
```c++
#include <opencog/atomspace/AtomSpace.h>
#include <opencog/atoms/execution/ExecutionOutputLink.h>
#include <opencog/rule-engine/backwardchainer/BackwardChainer.h>
#include <opencog/truthvalue/SimpleTruthValue.h>

using namespace opencog;

AtomSpace _as;
#define N _as.add_node
#define L _as.add_link

Handle* id1(AtomSpace* as, Handle* params)
{
	if(params->atom_ptr()->get_type() != LIST_LINK) return params;
	return new Handle(params->atom_ptr()->getOutgoingSet()[0]);
}

void conf();

int main()
{
	setLocalFunc("id2", id1);
	setLocalFunc("id4", id1);
	conf();
	ure_logger().set_level("DEBUG");
	Handle src2 =
		L(EVALUATION_LINK,
			N(PREDICATE_NODE, "ExpandTo"),
		L(LIST_LINK,
				L(NUMERIC_OUTPUT_LINK,
					N(CONCEPT_NODE, "Gradient"),
					L(NUMERIC_OUTPUT_LINK, N(CONCEPT_NODE, "+"), N(NUMBER_NODE, "4"), N(NUMBER_NODE, "3"))),
				N(VARIABLE_NODE, "$X")));

	Handle rbs = N(CONCEPT_NODE, "my-rule-base");
	BackwardChainer bc(_as, rbs, src2);
	bc.do_chain();
	Handle result = bc.get_results();
	std::cout << result.atom_ptr()->to_string() << std::endl;
	return 0;
}

void set_rule1()
{
	Handle premise1 =
		L(NUMERIC_OUTPUT_LINK,
			N(CONCEPT_NODE, "Gradient"),
			L(NUMERIC_OUTPUT_LINK,
				N(CONCEPT_NODE, "+"), N(VARIABLE_NODE, "$F1"), N(VARIABLE_NODE, "$F2")));
	Handle premise2 =
		L(EVALUATION_LINK,
			N(PREDICATE_NODE, "ExpandTo"),
			L(LIST_LINK,
				L(NUMERIC_OUTPUT_LINK, N(CONCEPT_NODE, "Gradient"), N(VARIABLE_NODE, "$F1")),
				N(VARIABLE_NODE, "$EGX")));
	Handle premise3 =
		L(EVALUATION_LINK,
			N(PREDICATE_NODE, "ExpandTo"),
			L(LIST_LINK,
				L(NUMERIC_OUTPUT_LINK, N(CONCEPT_NODE, "Gradient"), N(VARIABLE_NODE, "$F2")),
				N(VARIABLE_NODE, "$EGY")));
	L(DEFINE_LINK,
		N(DEFINED_SCHEMA_NODE, "GradientSum"),
     	L(BIND_LINK,
      		L(VARIABLE_LIST,
       			N(VARIABLE_NODE, "$F1"),
       			N(VARIABLE_NODE, "$F2"),
       			N(VARIABLE_NODE, "$EGX"),
				N(VARIABLE_NODE, "$EGY")),
      		L(AND_LINK,
			  	premise1,
			  	premise2,
			  	premise3),
      		L(EXECUTION_OUTPUT_LINK,
       			N(GROUNDED_SCHEMA_NODE, "lib:\\id4"),
       			L(LIST_LINK,
        			L(EVALUATION_LINK,
         				N(PREDICATE_NODE, "ExpandTo"),
         				L(LIST_LINK,
          					L(NUMERIC_OUTPUT_LINK,
							  	N(CONCEPT_NODE, "Gradient"),
							  		L(NUMERIC_OUTPUT_LINK, N(CONCEPT_NODE, "+"), N(VARIABLE_NODE, "$F1"), N(VARIABLE_NODE, "$F2"))),
          					L(NUMERIC_OUTPUT_LINK, N(CONCEPT_NODE, "+"), N(VARIABLE_NODE, "$EGX"), N(VARIABLE_NODE, "$EGY")))),
					premise1, premise2, premise3))));

}

void set_rule2()
{
	Handle premise1 = L(NUMERIC_OUTPUT_LINK,
		N(CONCEPT_NODE, "Gradient"),
		N(VARIABLE_NODE, "$F0"));

	L(DEFINE_LINK,
    	N(DEFINED_SCHEMA_NODE, "GradientAny"),
     	L(BIND_LINK,
      		L(VARIABLE_LIST,
       			L(TYPED_VARIABLE_LINK, N(VARIABLE_NODE, "$F0"), N(TYPE_NODE, "NumberNode"))),
			L(AND_LINK, premise1),
      		L(EXECUTION_OUTPUT_LINK,
       			N(GROUNDED_SCHEMA_NODE, "lib:\\id2"),
       			L(LIST_LINK,
        			L(EVALUATION_LINK,
						N(PREDICATE_NODE, "ExpandTo"),
						L(LIST_LINK, premise1, N(NUMBER_NODE, "0"))),
        			L(NUMERIC_OUTPUT_LINK, N(CONCEPT_NODE, "Gradient"), N(VARIABLE_NODE, "$F0"))
        ))
      ));
}

void conf()
{
	L(EXECUTION_LINK,
   		N(SCHEMA_NODE, "URE:maximum-iterations"),
   		N(CONCEPT_NODE, "my-rule-base"),
   		N(NUMBER_NODE, "1000"));
	L(INHERITANCE_LINK, N(CONCEPT_NODE, "my-rule-base"), N(CONCEPT_NODE, "URE"));
	TruthValuePtr stv = SimpleTruthValue::createTV(0.4, 1.0);
	Handle grad_sum = N(DEFINED_SCHEMA_NODE, "GradientSum");
	grad_sum.atom_ptr()->setTruthValue(stv);
	L(MEMBER_LINK, grad_sum, N(CONCEPT_NODE, "my-rule-base"));
	Handle grad_any = N(DEFINED_SCHEMA_NODE, "GradientAny");
	grad_any.atom_ptr()->setTruthValue(stv);
	L(MEMBER_LINK, grad_any, N(CONCEPT_NODE, "my-rule-base"));
	set_rule1();
	set_rule2();
}
```
At some point, URE correctly finds a solution:
```
[2018-09-18 13:04:45:857] [DEBUG] [URE] Expanded forward chainer strategy:
(BindLink
  (AndLink
    (NumericOutputLink
      (ConceptNode "Gradient") ; [3591855150658774384][1]
      (NumberNode "4.000000") ; [6913895523703723370][1]
    ) ; [17281436908051613321][9]
  ) ; [12907163332344424193][9]
  (ExecutionOutputLink
    (GroundedSchemaNode "lib:\id4") ; [3729477787633347453][1]
    (ListLink
      (EvaluationLink
        (PredicateNode "ExpandTo") ; [1996310950776182335][1]
        (ListLink
          (NumericOutputLink
            (ConceptNode "Gradient") ; [3591855150658774384][1]
            (NumericOutputLink
              (ConceptNode "+") ; [8340788501503500475][1]
              (NumberNode "4.000000") ; [6913895523703723370][1]
              (NumberNode "3.000000") ; [2390611616569436914][1]
            ) ; [12002400972042032902][1]
          ) ; [10373204325581446757][1]
          (NumericOutputLink
            (ConceptNode "+") ; [8340788501503500475][1]
            (NumberNode "0.000000") ; [4895729370997130312][1]
            (NumberNode "0.000000") ; [4895729370997130312][1]
          ) ; [13465867471884890746][9]
        ) ; [13009094634721151402][9]
      ) ; [14305701287695354470][9]
      (NumericOutputLink
        (ConceptNode "Gradient") ; [3591855150658774384][1]
        (NumericOutputLink
          (ConceptNode "+") ; [8340788501503500475][1]
          (NumberNode "4.000000") ; [6913895523703723370][1]
          (NumberNode "3.000000") ; [2390611616569436914][1]
        ) ; [12002400972042032902][1]
      ) ; [10373204325581446757][1]
      (ExecutionOutputLink
        (GroundedSchemaNode "lib:\id2") ; [3729477787633347453][1]
        (ListLink
          (EvaluationLink
            (PredicateNode "ExpandTo") ; [1996310950776182335][1]
            (ListLink
              (NumericOutputLink
                (ConceptNode "Gradient") ; [3591855150658774384][1]
                (NumberNode "4.000000") ; [6913895523703723370][1]
              ) ; [17281436908051613321][9]
              (NumberNode "0.000000") ; [4895729370997130312][1]
            ) ; [17749342224157327004][9]
          ) ; [17898995397459085336][9]
          (NumericOutputLink
            (ConceptNode "Gradient") ; [3591855150658774384][1]
            (NumberNode "4.000000") ; [6913895523703723370][1]
          ) ; [17281436908051613321][9]
        ) ; [11943390574856327244][9]
      ) ; [12884216768079149585][9]
      (ExecutionOutputLink
        (GroundedSchemaNode "lib:\id2") ; [3729477787633347453][1]
        (ListLink
          (EvaluationLink
            (PredicateNode "ExpandTo") ; [1996310950776182335][1]
            (ListLink
              (NumericOutputLink
                (ConceptNode "Gradient") ; [3591855150658774384][1]
                (NumberNode "3.000000") ; [2390611616569436914][1]
              ) ; [9315494789057156625][1]
              (NumberNode "0.000000") ; [4895729370997130312][1]
            ) ; [9545095938764793380][9]
          ) ; [18299058626202437024][9]
          (NumericOutputLink
            (ConceptNode "Gradient") ; [3591855150658774384][1]
            (NumberNode "3.000000") ; [2390611616569436914][1]
          ) ; [9315494789057156625][1]
        ) ; [9340389082842130972][9]
      ) ; [14160055767478014433][9]
    ) ; [11550953700195247048][9]
  ) ; [12775635404415766541][9]
) ; [11671183528972663481][9]
```
However, it doesn't consider it as such:
```
[2018-09-18 13:04:45:857] [DEBUG] [URE] Selected and-BIT for fulfillment (fcs value):
[11671183528972663481][9]
[2018-09-18 13:04:45:857] [DEBUG] [URE] Results:
size = 0
```
That is, `fulfill_fcs(andbit->fcs)` is called with this solution, but `bindlink(&tmp_as, fcs)` in `fulfill_fcs` returns an empty set.
Even more interestingly, the found solution if being passed to `cog-execute!` in Scheme (with corresponding replacement of GroundedSchemaNode from "lib:" to "scm:") returns the correct result:
```scheme
$1 = (SetLink
   (EvaluationLink
      (PredicateNode "ExpandTo")
      (ListLink
         (NumericOutputLink
            (ConceptNode "Gradient")
            (NumericOutputLink
               (ConceptNode "+")
               (NumberNode "4.000000")
               (NumberNode "3.000000")
            )
         )
         (NumericOutputLink
            (ConceptNode "+")
            (NumberNode "0.000000")
            (NumberNode "0.000000")
         )
      )
   )
)
```
Why doesn't it work in URE? One possible reason is that `andbit->fcs` is not presented in `tmp_as` created in `fulfill_fcs`.
Indeed, if we add something like
```c++
tmp_as.add_link(BIND_LINK, fcs.const_atom_ptr()->getOutgoingSet()[0], fcs.const_atom_ptr()->getOutgoingSet()[1]); //warning: different number of arguments is possible
```
after `AtomSpace tmp_as(&_as);` in `BackwardChainer::fulfill_fcs`, the program begins to work and returns the correct result:
```scheme
(SetLink
  (EvaluationLink
    (PredicateNode "ExpandTo") ; [1996310950776182335][1]
    (ListLink
      (NumericOutputLink
        (ConceptNode "Gradient") ; [3591855150658774384][1]
        (NumericOutputLink
          (ConceptNode "+") ; [8340788501503500475][1]
          (NumberNode "4.000000") ; [6913895523703723370][1]
          (NumberNode "3.000000") ; [2390611616569436914][1]
        ) ; [12002400972042032902][1]
      ) ; [10373204325581446757][1]
      (NumericOutputLink
        (ConceptNode "+") ; [8340788501503500475][1]
        (NumberNode "0.000000") ; [4895729370997130312][1]
        (NumberNode "0.000000") ; [4895729370997130312][1]
      ) ; [13465867471884890746][1]
    ) ; [13009094634721151402][1]
  ) ; [14305701287695354470][1]
) ; [13955625238458164458][1]
```
I'm not sure if this is a good approach to solve the problem, and why this problem doesn't pop up in other applications of URE...

**Comment by ngeiswei** [comment] 2018-09-19 11:01
Good catch! So there are 2 solutions
1. Fix the pattern matcher so that it properly handles queries outside of queried atomspace.
2. As you suggest, add `fcs` to `tmp_as`.

Going with 2. shouldn't have undesirable side effect, and its by far the simplest option. And the other handle it might hide a bigger problem in the pattern matcher (I've been aware of that sort of problems before, might be a rabbit hole we don't want to enter just yet, I don't know).

Finally, just to be clear, regardless of the you route you take, please add a unit test for that issue.

**Comment by Necr0x0Der** [comment] 2018-09-19 11:28
@ngeiswei , I'm not sure that this is the problem of Pattern Matcher. The solution here has a form of BindLink with premise:
```
  (AndLink
    (NumericOutputLink
      (ConceptNode "Gradient") ; [3591855150658774384][1]
      (NumberNode "4.000000") ; [6913895523703723370][1]
    ) ; [17281436908051613321][9]
  ) ; [12907163332344424193][9]
```
Thus, Pattern Matcher wants to find a matching for this premise in Atomspace and can't find it, because intermediate URE results are not stored in the original Atomspace. So, the behavior of Pattern Matcher seems correct. On contrary, one can say that its behavior is incorrect when we write the corresponding binding link in Scheme and get the result, because Pattern Matcher matches the premise to itself since this binding link is stored in the Atomspace. Worse, Pattern Matcher can find groundings in other queries. E.g., if we add another query in the original example:
```
Handle src3 = L(EVALUATION_LINK, N(PREDICATE_NODE, "ExpandTo"),
            L(LIST_LINK, L(NUMERIC_OUTPUT_LINK, N(CONCEPT_NODE, "Gradient"), N(NUMBER_NODE, "3")),
                               N(VARIABLE_NODE, "$X")));
```
then URE will find another "solution":
```
(EvaluationLink
      (PredicateNode "ExpandTo")
      (ListLink
         (NumericOutputLink
            (ConceptNode "Gradient")
            (NumericOutputLink
               (ConceptNode "+")
               (NumberNode "4.000000")
               (NumberNode "3.000000")
            )
         )
         (NumericOutputLink
            (ConceptNode "+")
            (NumberNode "0.000000")
            (VariableNode "$X")
         )
      )
   )
```
that has not too much sense.
So, in our case, we shouldn't fix Pattern Matcher to return a result when it can't find a matching subgraph into Atomspace to a premise (even it doesn't contain variables). On the contrary, I would place queries outside Atomspace, so one query coulnd't use subgraphs from another query (or from itself) as answer.
A better way for our case would be to place not the and-BIT for fulfillment into the temporary Atomspace, but intermediate results of inference, but it might be much more tricky. 
For now, I'd add `fcs` to `tmp_as` as a safest not solution, but workaround if it will not cause other problems.

**Comment by ngeiswei** [comment] 2018-09-19 11:40
Oh, OK, I read too fast... Yeah, don't add `fcs` to `tmp_as` just yet, I need to fully understand why the BC doesn't deal correctly with that.

**Comment by ngeiswei** [comment] 2018-09-19 11:48
I wonder if the problem isn't that
```
    (NumericOutputLink
      (ConceptNode "Gradient") ; [3591855150658774384][1]
      (NumberNode "4.000000") ; [6913895523703723370][1]
    ) ; [17281436908051613321][9]
```
should be absent from the set of clauses of the `BindLink`. Maybe the use of `NumericOutputLink` is confusing the BC.

Could you create a unit test for it and push it to a branch beside master (on your personal fork) and I would like to try to have a look at it. If the problem is deeper in the BC I would rather bite the bullet and provide a proper fix than a temporary hack.

**Comment by ngeiswei** [comment] 2018-09-19 11:49
I mean, I'm perfectly happy if you fix it rather than I, but creating a unit test is the first step anyway...

**Comment by Necr0x0Der** [comment] 2018-09-19 13:32
> I wonder if the problem isn't that should be absent from the set of clauses of the `BindLink`. Maybe the use of `NumericOutputLink` is confusing the BC.

I have had this idea, but didn't investigate it. Will do as time permits...

**Comment by Necr0x0Der** [comment] 2018-09-25 08:54
OK, so the question is why
```
(NumericOutputLink
      (ConceptNode "Gradient") ; [3591855150658774384][1]
      (NumberNode "4.000000") ; [6913895523703723370][1]
    ) ; [17281436908051613321][9]
```
is among the set of clauses of the `BindLink`.
This `BindLink` is formed in `expand_fcs`, which actually calls `Unify::remove_constant_clauses`, which calls `is_constant`, which checks if the clause is really constant AND if it is in the query atomspace. The clause IS considered a constant, but it ISN'T in the query atomspace. There is a simple 'hack' to solve this - either by adding NumericOutput to the list of exceptions, or to add the premise to the query atomspace, but this might be not a good solution. I wonder why some Atom types are considered as exceptions, while others are not...
One can also consider the rule set in the example as incorrect, since the rules have premises that are grounded backwardly in the conclusions of other premises, but most deep premises like the one above cannot be grounded in atomspace knowledge base. Indeed, one can say that URE/PM works correctly here, because to prove the whole chain it needs to 'prove' that constant premise, and it has no means to do this. But this is quite a general case if we want to apply URE for chaining symbolic transformations. However, maybe it can be fixed by adding some additional dumb rule, which will be able to infer any NumericOutputLink for "Gradient"... I'll try this and report a little bit later.

**Comment by ngeiswei** [comment] 2018-09-25 11:34
@Necr0x0Der could you create a unit test out of it? If you don't have time just let me know and I'll do it. Having a unit test makes it easier to debug as it allows to pretty print atoms as you step into the code.

**Comment by Necr0x0Der** [comment] 2018-09-25 16:14
@ngeiswei , simply inserting `(NumericOutputLink (ConceptNode "Gradient") (NumberNode "4"))` and same for 3 solves the problem. So, apparently, the problem is that these premises cannot be proven/inferred by URE. My first thought was to add one more rule that says that any such construct is inferrable, but this rule will have an empty premise, and I'm not sure this is a good idea. The next idea was to use ForAllLink to specify a predicate that is true for all inputs, but it didn't worked out.
However, the solution was even simpler: we just need to replace the line `L(AND_LINK, premise1),` in the second rule (where premise1 is `L(NUMERIC_OUTPUT_LINK, N(CONCEPT_NODE, "Gradient"), N(VARIABLE_NODE, "$F0"))`) with `L(AND_LINK, N(VARIABLE_NODE, "$F0")),`. So, we just say that in order to apply the rule, we need to have a number node (which is in atomspace), but not this number node wrapped into "Gradient" (which is not in atomspace).
I don't like this solution to full extent, but it is satisfactory. I'm not totally happy, because if we try to apply Forward chainer, it will wrap every number node into NumericOutput with "Gradient"...
In any case, Backward Chainer works as intended, and there is no need to introduce changes to solve the problem. Although application of URE to this example is somewhat cumbersome, one case is not enough to come up with a more convenient way of using URE for symbolic transformations... So, I propose to close this issue as a non-issue. OK? I will commit the final example to singnet/semantic-vision repo later. If you think it is useful for atomspace repo as an example or unit test, let me know.

**Comment by ngeiswei** [comment] 2018-09-27 06:19
@Necr0x0Der could you paste the definition of `id4` which is missing (otherwise I guess I have it in one of our prior exchange)?

**Comment by ngeiswei** [comment] 2018-09-27 06:30
@Necr0x0Der why do you set the TV of `grad_sum` and `grad_any`?

Also, note that you don't need to take the atom pointer associated to a Handle to call its methods, you may directly write
```c++
grad_sum->setTruthValue(stv);
```

**Comment by ngeiswei** [comment] 2018-09-27 06:48
Note also that when using the C++ API you don't need to put the parameters in the atomspace, for instance instead of
```c++
	L(EXECUTION_LINK,
   		N(SCHEMA_NODE, "URE:maximum-iterations"),
   		N(CONCEPT_NODE, "my-rule-base"),
   		N(NUMBER_NODE, "1000"));
```
you may just write
```c++
	bc.get_config().set_maximum_iterations(1000);
```

**Comment by ngeiswei** [comment] 2018-09-27 07:17
@Necr0x0Der never mind for `id4`, I understand now...

**Comment by ngeiswei** [comment] 2018-09-27 07:36
@ngeiswei said
> @Necr0x0Der why do you set the TV of grad_sum and grad_any?

I suppose it was to assign a weight to the rule, but note that the TV must be assigned to
```
Member <TV>
  <rule>
  <rbs>
```
not `<rule>.

**Comment by ngeiswei** [comment] 2018-09-27 08:56
Also note that you don't need a `VariableList` when there is only one variable.

**Comment by Necr0x0Der** [comment] 2018-09-27 10:28
@ngeiswei , `id4` is grounded in the same C++ function. I introduced it in order to make URE log easier transformable to a workable Scheme code. To have `VariableList` is more convenient for experimenting with different number of variables.
Thanks for other comments. They are useful.

**Comment by ngeiswei** [comment] 2018-09-28 12:49
@Necr0x0Der, as you intuited, the URE is indeed not as fault. The problem comes from the fact that premises such as
```
NumericOutput
  Gradient
  F
```
are actually not required (and in fact harmful), indeed such fact is already true, because such construct is always possible. The most you could do is to have premises to make sure that `F` is well-formed, but that is not what such facts tell.

The unit test in #31 contains the corrected rules.

**Comment by ngeiswei** [comment] 2018-09-28 12:53
@Necr0x0Der said
> I don't like this solution to full extent, but it is satisfactory. I'm not totally happy, because if we try to apply Forward chainer, it will wrap every number node into NumericOutput with "Gradient"...

Yes, it is known problem by myself. In order to avoid it I define 2 types rules, one for the backward chainer, and one for the forward chainer (or rather one should say for the iterative forward chainer, indeed currently the forward chainer is not a true forward chainer but rather a loop that applies the rules iteratively). For the forward chainer I call them *evaluation*, and for the backward chainer I call them *introduction*.

**Comment by ngeiswei** [comment] 2018-09-28 13:00
Here's an example of evaluation rule

https://github.com/singnet/opencog/blob/master/opencog/pln/rules/wip/closed-lambda-evaluation.scm

and the corresponding rule as an introduction

https://github.com/singnet/opencog/blob/master/opencog/pln/rules/wip/closed-lambda-introduction.scm

**Closed** 2018-09-28 13:01 UTC
Labels: URE, bug

**Comment by Necr0x0Der** [comment] 2018-09-28 13:18
@ngeiswei : 
> 
> The most you could do is to have premises to make sure that `F` is well-formed, but that is not what such facts tell.

Yes, this is what I've also done.

> 
> The unit test in #31 contains the corrected rules.

Thanks. One minor remark - it is useful to have this wrapper instead of `Gradient = N(CONCEPT_NODE, "Gradient");`:
```c++
Handle GradientOf(const Handle& atom)
{
	return L(NUMERIC_OUTPUT_LINK, N(CONCEPT_NODE, "Gradient"), atom);
	//return L(EVALUATION_LINK, N(PREDICATE_NODE, "Gradient"), atom);
}
```
because one can easily try to use predicate nodes instead of numeric output links and see that the result is same...
Also, wrapping "+" in a similar way can make code slightly shorter and easier to modify:
```c++
Handle Plus(const Handle& atom)
{
	return L(NUMERIC_OUTPUT_LINK, N(CONCEPT_NODE, "Plus"), atom);
}
```
so one can simply write `GradientOf(Plus(F1,F2))`
